1.SELECT EMPNO,ENAME,JOB,HIREDATE
FROM EMP;

Save p1q7.sql [create|replace]

2.@p1q7.sql

3.SELECT UNIQUE JOB
FROM EMP;

4.GET p1q7.sql

SELECT EMPNO "Emp #",ENAME "Employee",JOB "Job",HIREDATE "Hire Date"
FROM EMP;

5.SELECT ENAME || ', ' || JOB "Employee and Title"
FROM Emp;

6.SELECT EMPNO || ',' || ENAME || ',' || JOB || ',' || MGR || ',' || HIREDATE || ',' || SAL || ',' || COMM || ',' || DEPTNO "THE_OUTPUT" 
from Emp;

7.SELECT ENAME,JOB,HIREDATE
FROM Emp
WHERE HIREDATE BETWEEN '20-feb-1981' and '01-may-1981'
ORDER BY HIREDATE;

8.SELECT ENAME,DEPTNO
FROM Emp
WHERE DEPTNO IN (10,30)
ORDER BY ENAME;

9.SELECT ENAME "Employee",SAL "Montly Salary"
FROM Emp
WHERE SAL>1500 AND DEPTNO IN (10,30);

10.SELECT ENAME,HIREDATE
FROM Emp
WHERE HIREDATE >= '01-JAN-1982' AND HIREDATE =< '31-dec-1982';

11.SELECT ENAME,JOB
FROM Emp
WHERE MGR IS NULL OR MGR=0;

12.SELECT ENAME,SAL,COMM 
FROM EMP 
WHERE COMM != 0 AND COMM IS NOT NULL 
ORDER BY SAL DESC, COMM DESC;

13.SELECT ENAME
FROM Emp
WHERE ENAME LIKE '%L%L%' AND DEPTNO=30 OR MGR=7782;

14.SELECT ENAME,JOB,SAL 
FROM EMP 
WHERE JOB in ('CLERK','ANALYST') AND SAL NOT IN(1000,3000,5000);

15.SELECT ENAME,SAL,COMM
FROM Emp
WHERE COMM>(SAL+SAL*0.1);